// ocelote/src/app/components/navbar.tsx
"use client";

import Link from "next/link";
import Image from "next/image";

const Navbar: React.FC = () => {
  return (
    <nav className="sticky top-0 z-10 bg-black">
      <div className="flex w-screen h-16 items-center p-8">
        <Link href="/">
          <Image
            src="/logo/ocelote-logo-blanco4x.png"
            height={30}
            width={300}
            alt="Ocelote Logo"
          />
        </Link>
        
        <div className="w-full flex flex-row-reverse">
          <ul className="flex flex-row text-white">
            <li className="px-4">
              <Link href="/">ABOUT US</Link>
            </li>
            <li className="px-4">
              <Link href="/pages/projects">PROJECTS</Link>
            </li>
            <li className="px-4">
              <Link href="/">CONTACT US</Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// ocelote-portafolio/src/app/components/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav-bar',
  imports: [],
  templateUrl: './nav-bar.component.html'
})
export class NavBarComponent {

}

<nav class="sticky top-0 z-10">
    <div class="flex w-screen h-16 items-center p-8 bg-black">
        <img src="/logo/ocelote logo.png" class="h-6">
        <div class="w-full flex flex-row-reverse text-white font-bold">
            <ul class="flex flex-row">
                <li class="px-4">
                    <a>ABOUT US</a>
                </li>
                <li class="px-4">
                    <a>PROJECTS</a>
                </li>
                <li class="pl-4">
                    <a>CONTACT US</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
